docker-compose backup

  redis:
    image: redis:latest
    container_name: monitor_redis
    restart: always
    ports:
      - '6379:6379'
    env_file: '.env'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
  adminer:
      image: adminer
      ports:
        - "8080:8080"